
FROM python:3.8.10 

ENV REDIS_IP=redis-db

RUN pip install Flask==2.2.2

RUN pip install hotqueue==0.2.8

RUN pip install redis==4.5.1

RUN pip install requests==2.26.0

RUN pip install DateTime==5.0

RUN pip install pyyaml==6.0

ADD ./worker.py /worker.py

ADD ./jobs.py /jobs.py

CMD ["python", "/worker.py"]
