
---
version: "3" 

services:
        redis-db:
                image: redis-7
                ports:
                        - 6379:6379
                volumes:
                        - ./data:/data
                user: "1000:1000"
        flask-app:
                build:
                  context: ./
                  dockerfile: ./Dockerfile.api
                depends_on:
                    - redis-db
                ports:
                    - 5000:5000
                image: khanks/fireball_api:1.1
                volumes:
                    - ./config.yaml:/config.yaml
                environment:
                    - REDIS_IP=redis-db


