---
apiVersion: v1
kind: Service
metadata:
        name: app-test-service
spec:
        type: ClusterIP
        selector:
                app: app-test-redis
        ports:
                - name: app-test-redis
                  port: 6379
                  targetPort: 6379
